version: '2.1'

services:
  db-node-1:
    build:
      context: mariadb
      dockerfile: Dockerfile
    container_name: db-node-1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    networks:
      - arch-network
    ports:
      - 3360:3306
    healthcheck:
      test: "/usr/bin/mariadb --user=stud --password=stud --execute \"SHOW DATABASES;\""
      interval: 15s
      timeout: 1s
      retries: 5
    volumes:
      - db-node-1-data:/var/lib/mysql

  db-node-2:
    build:
      context: mariadb
      dockerfile: Dockerfile
    container_name: db-node-2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    networks:
      - arch-network
    ports:
      - 3361:3306
    healthcheck:
      test: "/usr/bin/mariadb --user=stud --password=stud --execute \"SHOW DATABASES;\""
      interval: 15s
      timeout: 1s
      retries: 5
    volumes:
      - db-node-2-data:/var/lib/mysql


  proxysql:
    build:
      context: proxysql
      dockerfile: Dockerfile
    container_name: proxysql
    command: >
      --initial
    volumes:
      - proxysql-data:/var/lib/proxysql
    healthcheck:
      test: "mysql --user=admin --password=admin -h 127.0.0.1 --port=6032 --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    networks:
      - arch-network
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"
    depends_on:
      db-node-1:
        condition: service_healthy
      db-node-2:
        condition: service_healthy
    
  user_service:
    build:
      context: user_service
      dockerfile: Dockerfile
    container_name: user_service
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
      - SHARDS_COUNT=2
    ports:
      - 8081:8081
    healthcheck:
      test: curl -sS http://localhost:8081/ || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
    networks:
      - arch-network
    depends_on:
      proxysql:
        condition: service_healthy

  product_service:
    build:
      context: product_service
      dockerfile: Dockerfile
    container_name: product_service
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
      - SHARDS_COUNT=2
    ports:
      - 8082:8082
    healthcheck:
      test: curl -sS http://localhost:8082/ || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
    networks:
      - arch-network
    depends_on:
      proxysql:
        condition: service_healthy
      user_service:
        condition: service_healthy

  basket_service:
    build:
      context: basket_service
      dockerfile: Dockerfile
    container_name: basket_service
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
      - SHARDS_COUNT=2
    ports:
      - 8084:8084
    healthcheck:
      test: curl -sS http://localhost:8084/ || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
    networks:
      - arch-network
    depends_on:
      proxysql:
        condition: service_healthy
      user_service:
        condition: service_healthy
      product_service:
        condition: service_healthy
volumes:
  db-node-1-data:
  db-node-2-data:
  proxysql-data:

networks:
  arch-network:
    driver: "bridge"
    external: false